<?php

return [
    'templates' => [
        [
            'slug' => 'web-research',
            'title' => 'Internetonderzoek',
            'description' => 'Zoek actuele informatie, vergelijk bronnen en geef een duidelijke conclusie.',
            'category' => 'Research',
            'icon' => '🌐',
            'mode' => 'research',
            'prompt' => 'Onderzoek dit onderwerp uitgebreid op internet. Gebruik meerdere betrouwbare en recente bronnen, benoem belangrijke verschillen tussen bronnen, geef onzekerheden aan en eindig met een duidelijke samenvatting en bronverwijzingen: ',
        ],
        [
            'slug' => 'quick-web',
            'title' => 'Snel opzoeken',
            'description' => 'Zoek de nieuwste informatie op internet en vat die kort samen.',
            'category' => 'Research',
            'icon' => '🔎',
            'mode' => 'web',
            'prompt' => 'Zoek dit op internet en geef mij de nieuwste betrouwbare informatie met bronnen: ',
        ],
        [
            'slug' => 'document-explain',
            'title' => 'Document uitleggen',
            'description' => 'Laat een PDF, Word-, Excel- of PowerPoint-bestand begrijpelijk uitleggen.',
            'category' => 'Documenten',
            'icon' => '📄',
            'mode' => 'auto',
            'prompt' => 'Analyseer het bestand dat ik toevoeg. Leg in eenvoudige taal uit wat erin staat, benoem de belangrijkste punten, opvallende risico’s of fouten en geef daarna een korte samenvatting.',
        ],
        [
            'slug' => 'document-action-points',
            'title' => 'Actiepunten uit document',
            'description' => 'Haal taken, deadlines, bedragen en belangrijke afspraken uit een document.',
            'category' => 'Documenten',
            'icon' => '✅',
            'mode' => 'auto',
            'prompt' => 'Lees het bestand dat ik toevoeg en haal er alle concrete actiepunten uit. Noem per actie wie verantwoordelijk lijkt, eventuele deadline, bedragen, voorwaarden en ontbrekende informatie.',
        ],
        [
            'slug' => 'email-professional',
            'title' => 'Professionele e-mail',
            'description' => 'Maak een duidelijke, natuurlijke zakelijke e-mail.',
            'category' => 'Schrijven',
            'icon' => '✉️',
            'mode' => 'plain',
            'prompt' => 'Schrijf een professionele maar natuurlijke e-mail op basis van mijn informatie. Houd de toon vriendelijk en direct. Geef alleen de onderwerpregel en de e-mailtekst. Dit wil ik zeggen: ',
        ],
        [
            'slug' => 'rewrite',
            'title' => 'Tekst verbeteren',
            'description' => 'Maak tekst duidelijker, professioneler en natuurlijker zonder betekenis te verliezen.',
            'category' => 'Schrijven',
            'icon' => '✨',
            'mode' => 'plain',
            'prompt' => 'Herschrijf de volgende tekst zodat hij duidelijk, professioneel en natuurlijk klinkt. Behoud de betekenis en belangrijke details. Tekst: ',
        ],
        [
            'slug' => 'translate-nl-en-ur',
            'title' => 'Vertalen NL / EN / اردو',
            'description' => 'Vertaal natuurlijk tussen Nederlands, Engels en Urdu.',
            'category' => 'Taal',
            'icon' => '🌍',
            'mode' => 'plain',
            'prompt' => 'Vertaal de tekst die ik geef naar de taal die ik noem. Behoud betekenis, toon en namen. Geef alleen de vertaling tenzij uitleg nodig is. Tekst: ',
        ],
        [
            'slug' => 'code-review',
            'title' => 'Code review',
            'description' => 'Zoek bugs, securityproblemen en verbeterpunten in code.',
            'category' => 'Code',
            'icon' => '🧩',
            'mode' => 'code',
            'prompt' => 'Review mijn code grondig. Zoek bugs, securityproblemen, edge cases, performanceproblemen en onderhoudsproblemen. Leg concreet uit wat fout kan gaan en geef daarna verbeterde code. ',
        ],
        [
            'slug' => 'laravel-debug',
            'title' => 'Laravel fout oplossen',
            'description' => 'Analyseer Laravel/PHP errors en geef concrete herstelstappen.',
            'category' => 'Code',
            'icon' => '🛠️',
            'mode' => 'code',
            'prompt' => 'Analyseer deze Laravel/PHP fout stap voor stap. Bepaal de waarschijnlijkste oorzaak, geef veilige controlecommando’s en laat exact zien welk bestand of welke code aangepast moet worden. Fout/log: ',
        ],
        [
            'slug' => 'data-analysis',
            'title' => 'Data analyseren',
            'description' => 'Analyseer cijfers, tabellen of spreadsheets en zoek patronen.',
            'category' => 'Analyse',
            'icon' => '📊',
            'mode' => 'code',
            'prompt' => 'Analyseer deze data zorgvuldig. Controleer berekeningen, zoek trends, uitschieters en fouten en geef de belangrijkste conclusies. Gebruik berekeningen/code waar dat helpt. ',
        ],
        [
            'slug' => 'plan',
            'title' => 'Plan maken',
            'description' => 'Zet een doel om in een concreet stappenplan.',
            'category' => 'Productiviteit',
            'icon' => '🗂️',
            'mode' => 'plain',
            'prompt' => 'Maak van mijn doel een concreet stappenplan. Deel het op in logische fasen, geef prioriteiten, afhankelijkheden, risico’s en een praktische eerstvolgende stap. Mijn doel: ',
        ],
        [
            'slug' => 'compare-options',
            'title' => 'Opties vergelijken',
            'description' => 'Vergelijk meerdere mogelijkheden op duidelijke criteria.',
            'category' => 'Analyse',
            'icon' => '⚖️',
            'mode' => 'auto',
            'prompt' => 'Vergelijk de opties die ik geef. Maak de verschillen concreet op kosten, kwaliteit, risico, eenvoud, onderhoud en geschiktheid voor mijn doel. Benoem ook welke informatie nog ontbreekt. Opties: ',
        ],
        [
            'slug' => 'meeting-summary',
            'title' => 'Vergadering samenvatten',
            'description' => 'Maak samenvatting, besluiten en actiepunten van notities of transcript.',
            'category' => 'Productiviteit',
            'icon' => '📝',
            'mode' => 'plain',
            'prompt' => 'Maak van deze vergadernotities of transcript een compacte samenvatting met: belangrijkste onderwerpen, besluiten, open vragen, actiepunten, eigenaar en deadline indien genoemd. Inhoud: ',
        ],
        [
            'slug' => 'social-post',
            'title' => 'Social post',
            'description' => 'Maak een korte post voor LinkedIn, Instagram of andere social media.',
            'category' => 'Marketing',
            'icon' => '📣',
            'mode' => 'plain',
            'prompt' => 'Maak een sterke social-media post van mijn informatie. Geef een duidelijke hook, natuurlijke tekst, passende call-to-action en alleen relevante hashtags. Platform/doel: ',
        ],
        [
            'slug' => 'seo-page',
            'title' => 'SEO landingspagina',
            'description' => 'Maak een duidelijke SEO-pagina met headings, intentie en CTA.',
            'category' => 'Marketing',
            'icon' => '🚀',
            'mode' => 'research',
            'prompt' => 'Maak een SEO-landingspagina voor dit onderwerp. Onderzoek indien nodig actuele zoekintentie en terminologie, maak een logische H1/H2-structuur, nuttige inhoud, FAQ en CTA. Onderwerp/doelgroep: ',
        ],
        [
            'slug' => 'image-prompt',
            'title' => 'Afbeeldingsprompt',
            'description' => 'Maak een sterke prompt voor een logo, productfoto of visual.',
            'category' => 'Creatief',
            'icon' => '🎨',
            'mode' => 'plain',
            'prompt' => 'Maak een gedetailleerde professionele prompt voor een afbeelding op basis van mijn idee. Beschrijf onderwerp, compositie, belichting, perspectief, achtergrond, stijl en gewenste verhouding. Idee: ',
        ],
    ],
];
