<style>
#guest-chat{--gc-bg:#0f1116;--gc-panel:#15181f;--gc-soft:#1d212b;--gc-line:rgba(255,255,255,.09);--gc-text:#f5f2eb;--gc-muted:#a7abb5;--gc-gold:#e7c28a;position:fixed;right:20px;bottom:max(20px,env(safe-area-inset-bottom));z-index:1000;font:14px/1.55 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--gc-text);color-scheme:dark}
#guest-chat,#guest-chat *{box-sizing:border-box}#guest-chat[hidden],#guest-chat [hidden]{display:none!important}#guest-chat button,#guest-chat textarea{font:inherit}#guest-chat button{cursor:pointer}#guest-chat button:disabled{opacity:.5;cursor:wait}#guest-chat :is(button,a,textarea):focus-visible{outline:2px solid var(--gc-gold);outline-offset:2px}
.guest-chat__toggle{position:relative;display:flex;align-items:center;gap:11px;min-height:60px;padding:9px 16px 9px 9px;border:1px solid rgba(231,194,138,.32);border-radius:20px;background:linear-gradient(135deg,#24221d,#111318);color:var(--gc-text);box-shadow:0 14px 42px rgba(0,0,0,.38);transition:transform .16s ease,border-color .16s ease}.guest-chat__toggle:hover{transform:translateY(-2px);border-color:rgba(231,194,138,.55)}
.gc-icon{display:grid;place-items:center;width:42px;height:42px;flex:0 0 42px;border-radius:13px;background:linear-gradient(135deg,#f4dcad,#cf9c53);color:#281d0d}.gc-icon svg{width:21px;height:21px}.gc-launch-copy{display:flex;flex-direction:column}.gc-launch-copy strong{font-size:13px}.gc-launch-copy small{font-size:11px;color:#b8b1a6}.gc-launch-status{width:8px;height:8px;margin-left:4px;border-radius:50%;background:#48c774;box-shadow:0 0 0 4px rgba(72,199,116,.11)}
.gc-unread-badge{position:absolute;top:-7px;right:-7px;min-width:22px;height:22px;padding:0 6px;border:2px solid #111318;border-radius:999px;background:#ef4444;color:white;font-size:11px;font-weight:700;line-height:18px;text-align:center}
.guest-chat__panel{display:flex;flex-direction:column;width:min(410px,calc(100vw - 32px));height:min(660px,calc(100dvh - 105px));margin-bottom:12px;overflow:hidden;border:1px solid rgba(231,194,138,.22);border-radius:22px;background:var(--gc-bg);box-shadow:0 28px 90px rgba(0,0,0,.56)}
.guest-chat__header{display:flex;align-items:center;gap:10px;flex:0 0 auto;padding:14px;border-bottom:1px solid var(--gc-line);background:linear-gradient(135deg,#211f1a,#15171c)}.guest-chat__header .gc-icon{width:38px;height:38px;flex-basis:38px}.gc-title-wrap{min-width:0}.gc-title-row{display:flex;align-items:center;gap:8px}.gc-title-row h2{margin:0;font-size:15px;line-height:1.2}.gc-live-pill{display:inline-flex;align-items:center;gap:5px;color:#a9dfb9;font-size:10px}.gc-live-pill i{width:6px;height:6px;border-radius:50%;background:#47c875}.gc-subtitle{margin:3px 0 0;color:var(--gc-muted);font-size:11px}.gc-actions{display:flex;gap:2px;margin-left:auto}.gc-action{display:grid;place-items:center;width:38px;height:40px;padding:0;border:0;border-radius:10px;background:transparent;color:#bcc0c8}.gc-action:hover{background:rgba(255,255,255,.07);color:white}.gc-action svg{width:19px;height:19px}
.lc-modes{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:9px 12px;border-bottom:1px solid var(--gc-line);background:#11141a}.lc-modes button{min-height:39px;border:1px solid transparent;border-radius:10px;background:transparent;color:#9fa4ae}.lc-modes button[aria-pressed="true"]{border-color:rgba(231,194,138,.3);background:rgba(231,194,138,.1);color:#f0d5a7}
.gc-reset-confirm{display:flex;align-items:center;gap:8px;padding:9px 14px;border-bottom:1px solid var(--gc-line);background:#211d17;font-size:12px}.gc-reset-confirm button{padding:6px 9px;border:1px solid var(--gc-line);border-radius:8px;background:#111318;color:#f0d4a4}
.gc-body,.lc-panel{flex:1;min-height:0}.gc-body{overflow:auto;overscroll-behavior:contain;-webkit-overflow-scrolling:touch}.gc-welcome{padding:22px 19px 10px}.gc-eyebrow{margin:0 0 8px;color:var(--gc-gold);font-size:10px;letter-spacing:1.4px}.gc-welcome h3{margin:0 0 8px;font-size:27px;line-height:1.16;letter-spacing:-.7px}.gc-welcome>p:last-of-type{margin:0;color:var(--gc-muted);font-size:13px}.guest-chat__suggestions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:17px}.guest-chat__suggestions button{min-height:72px;padding:11px;border:1px solid var(--gc-line);border-radius:12px;background:rgba(255,255,255,.025);color:#dedbd4;text-align:left;font-size:12px}.guest-chat__suggestions button:hover{border-color:rgba(231,194,138,.42);background:rgba(231,194,138,.06)}.gc-topic{display:block;margin-bottom:3px;color:var(--gc-gold);font-size:9px}.guest-chat__messages{padding:10px 16px 4px}.gc-turn{margin-bottom:16px}.gc-turn--user{display:flex;flex-direction:column;align-items:flex-end}.gc-speaker{display:block;margin:0 0 4px 2px;color:#8f949f;font-size:9px}.guest-chat__message{width:fit-content;max-width:96%;margin:0;padding:11px 13px;border:1px solid var(--gc-line);border-radius:4px 14px 14px;background:var(--gc-soft);white-space:pre-wrap;overflow-wrap:anywhere}.guest-chat__message--user{border:0;border-radius:14px 4px 14px 14px;background:#e5c18a;color:#251b0d}.gc-copy{margin-top:5px;padding:4px 6px;border:0;background:transparent;color:#9ca1ab;font-size:10px}.gc-pending{margin:0 0 12px;color:var(--gc-gold);font-size:12px}
.gc-bottom{flex:0 0 auto;padding-top:8px;border-top:1px solid var(--gc-line);background:#111318}.gc-links{display:flex;justify-content:space-between;padding:0 16px 8px}.gc-links a{color:#9ca0a8;font-size:10px;text-decoration:none}.guest-chat__form{display:flex;align-items:flex-end;gap:7px;margin:0 12px;padding:6px;border:1px solid rgba(255,255,255,.16);border-radius:14px;background:#090b0e}.guest-chat__form:focus-within{border-color:rgba(231,194,138,.58)}.guest-chat__form textarea{display:block;resize:none;width:100%;min-width:0;height:42px;max-height:112px;padding:9px 7px;border:0;outline:0;background:transparent;color:var(--gc-text);font-size:16px;line-height:24px}.guest-chat__send{display:grid;place-items:center;width:42px;height:42px;flex:0 0 42px;padding:0;border:0;border-radius:10px;background:linear-gradient(135deg,#f2d6a1,#d3a359);color:#271b0b}.guest-chat__send svg{width:19px;height:19px}.guest-chat__notice{margin:0;padding:8px 12px 10px;color:#838893;text-align:center;font-size:9px}
.lc-panel{display:flex;flex-direction:column}.lc-status{margin:0;padding:10px 14px;border-bottom:1px solid var(--gc-line);color:#aaaeb7;font-size:11px}.lc-log{flex:1;min-height:0;overflow:auto;padding:14px;overscroll-behavior:contain;-webkit-overflow-scrolling:touch}.lc-error{margin:0;padding:8px 14px;color:#f2a7a7;font-size:11px}.lc-reopen{min-height:42px;margin:8px 12px;border:1px solid rgba(231,194,138,.35);border-radius:10px;background:#211d16;color:var(--gc-gold)}.lc-tool{display:grid;place-items:center;width:40px;height:42px;flex:0 0 40px;border:0;border-radius:9px;background:rgba(255,255,255,.05);color:#ddd;cursor:pointer}.lc-voice{border:0}.lc-msg{max-width:94%;margin:0 0 12px;padding:10px 11px;border-radius:13px 13px 13px 3px;background:#20232b}.lc-msg--visitor{margin-left:auto;border-radius:13px 13px 3px 13px;background:#e5c18a;color:#21180c}.lc-msg-head{display:flex;align-items:center;gap:7px;margin-bottom:6px}.lc-avatar{display:grid;place-items:center;width:26px;height:26px;flex:0 0 26px;overflow:hidden;border-radius:50%;background:#353946;font-size:10px}.lc-avatar img{width:100%;height:100%;object-fit:cover}.lc-msg p{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.lc-media-image,.lc-media-video{display:block;max-width:min(260px,100%);max-height:260px;border-radius:9px;object-fit:cover}.lc-file-link{color:inherit;text-decoration:underline}.lc-msg audio{width:min(260px,100%)}
.gc-incoming-toast{display:none;position:fixed;right:20px;bottom:94px;width:min(330px,calc(100vw - 32px));align-items:center;gap:10px;padding:12px;border:1px solid var(--gc-line);border-radius:15px;background:#151821;box-shadow:0 16px 45px rgba(0,0,0,.45)}.gc-incoming-toast.is-visible{display:flex}.gc-incoming-toast__icon{display:grid;place-items:center;width:34px;height:34px;flex:0 0 34px;border-radius:10px;background:rgba(231,194,138,.12);color:var(--gc-gold)}.gc-incoming-toast__icon svg{width:18px}.gc-incoming-toast strong,.gc-incoming-toast span span{display:block}.gc-incoming-toast span span{color:#aeb2bc;font-size:11px}.gc-incoming-toast__dot{width:7px;height:7px;margin-left:auto;border-radius:50%;background:#ef4444}
@media(min-width:700px){.guest-chat__panel[data-expanded="true"]{width:min(620px,calc(100vw - 42px));height:min(780px,calc(100dvh - 70px))}}
@media(max-width:699px){html.guest-chat-open{overflow:hidden;overscroll-behavior:none}#guest-chat{right:0;bottom:0;left:0;z-index:2147482000;pointer-events:none}#guest-chat>*{pointer-events:auto}.guest-chat__toggle{position:fixed;right:14px;bottom:max(14px,env(safe-area-inset-bottom));min-height:56px}.guest-chat__toggle .gc-launch-copy{display:none}.guest-chat__panel{position:fixed;left:0;right:0;top:var(--gc-viewport-top,0px);width:100%;height:var(--gc-viewport-height,100dvh);max-height:none;margin:0;border:0;border-radius:0;padding-top:env(safe-area-inset-top);padding-bottom:env(safe-area-inset-bottom);box-shadow:none}.guest-chat__header{padding:10px 12px}.gc-expand{display:none}.gc-welcome{padding-top:18px}.gc-welcome h3{font-size:25px}.guest-chat__suggestions{grid-template-columns:1fr}.guest-chat__suggestions button{min-height:58px}.gc-links{display:none}.guest-chat__form{margin:0 10px}.guest-chat__notice{padding-bottom:max(8px,env(safe-area-inset-bottom))}.gc-incoming-toast{right:12px;bottom:82px}}
@media(prefers-reduced-motion:reduce){#guest-chat *{transition:none!important;scroll-behavior:auto!important}}
</style>

<aside id="guest-chat" class="guest-chat" aria-label="Mashal chat" data-mode="ai" data-endpoint="{{ route('guest-chat.message') }}" data-live-script="{{ asset('js/live-chat.js') }}?v=22" data-calls-script="{{ asset('js/live-chat-calls.js') }}?v=19">
    <section id="guest-chat-panel" class="guest-chat__panel" aria-labelledby="guest-chat-title" hidden>
        <header class="guest-chat__header">
            <span class="gc-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"><path d="m12 3 2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6L12 3Z"/></svg></span>
            <div class="gc-title-wrap"><div class="gc-title-row"><h2 id="guest-chat-title">Mashal AI</h2><span class="gc-live-pill"><i></i>Online</span></div><p class="gc-subtitle">Slimme hulp, direct in je workspace</p></div>
            <div class="gc-actions">
                <button type="button" class="gc-action gc-reset" aria-label="Nieuw gesprek" title="Nieuw gesprek"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M12 5v14M5 12h14"/></svg></button>
                <button type="button" class="gc-action gc-expand" aria-label="Chat vergroten" aria-pressed="false" title="Chat vergroten"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M14 4h6v6M20 4l-7 7M10 20H4v-6m0 6 7-7"/></svg></button>
                <button type="button" class="gc-action guest-chat__close" aria-label="Chat sluiten" title="Chat sluiten"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="m6 6 12 12M18 6 6 18"/></svg></button>
            </div>
        </header>

        @if (\Illuminate\Support\Facades\Route::has('live-chat.show'))
            <div class="lc-modes" aria-label="Chatmodus">
                <button type="button" data-chat-mode="ai" aria-pressed="true">Mashal AI</button>
                <button type="button" data-chat-mode="human" aria-pressed="false">Medewerker</button>
            </div>
        @endif

        <div class="gc-reset-confirm" hidden><span>Dit gesprek wissen?</span><button type="button" data-reset-confirm>Wissen</button><button type="button" data-reset-cancel>Annuleren</button></div>

        <div class="gc-body">
            <div class="gc-welcome">
                <p class="gc-eyebrow">MASHAL INTELLIGENCE</p><h3>Wat wil je<br>bereiken?</h3><p>Vraag iets, werk een idee uit of krijg direct hulp met Mashal Studio.</p>
                <div class="guest-chat__suggestions" aria-label="Voorbeeldvragen">
                    <button type="button" data-question="Hoe kan ik een afbeelding uploaden en bewerken op Mashal Studio?"><span class="gc-topic">AFBEELDINGEN</span>Maak meer van je foto</button>
                    <button type="button" data-question="Help mij een professionele e-mail schrijven."><span class="gc-topic">SCHRIJVEN</span>Vind de juiste woorden</button>
                    <button type="button" data-question="Ik heb hulp nodig bij het inloggen op Mashal Studio."><span class="gc-topic">ACCOUNT</span>Hulp bij het inloggen</button>
                    <button type="button" data-question="Wat kan ik allemaal doen met Mashal Studio?"><span class="gc-topic">ONTDEKKEN</span>Leer de website kennen</button>
                </div>
            </div>
            <div class="guest-chat__messages" role="log" aria-live="polite" aria-relevant="additions" aria-label="Chatberichten"></div>
        </div>

        <div class="gc-bottom">
            <nav class="gc-links" aria-label="Handige pagina's"><a href="{{ route('contact') }}">Contact opnemen ↗</a><a href="{{ route('privacy') }}">Privacy</a></nav>
            <form class="guest-chat__form"><textarea rows="1" aria-label="Je bericht aan Mashal AI" placeholder="Vraag het Mashal AI…" maxlength="2000" required></textarea><button type="submit" class="guest-chat__send" aria-label="Bericht versturen"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 19V5m-6 6 6-6 6 6"/></svg></button></form>
            <p class="guest-chat__notice">AI kan fouten maken. Controleer belangrijke informatie.</p>
        </div>

        @if (\Illuminate\Support\Facades\Route::has('live-chat.show'))
            <section class="lc-panel" aria-label="Live chat met medewerker" hidden data-show="{{ route('live-chat.show') }}" data-store="{{ route('live-chat.store') }}" data-reopen="{{ route('live-chat.reopen') }}">
                <p class="lc-status" role="status">Live chat wordt gestart…</p><div class="lc-log" role="log" aria-live="polite" aria-relevant="additions" aria-label="Gesprek met medewerker"></div><p class="lc-error" role="status" hidden></p><button type="button" class="lc-reopen" hidden>Gesprek opnieuw openen</button>
                <form class="guest-chat__form lc-form"><label class="lc-tool" title="Bestand versturen" aria-label="Bestand versturen">📎<input class="lc-file" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/*,.mp4,.webm,.mov,.m4v,.avi,.mkv,.mpeg,.mpg,.3gp,.3g2,.ogv,.ts,.mts,.m2ts,.flv,.wmv,application/pdf,text/plain,.doc,.docx,.xls,.xlsx" hidden></label><button class="lc-tool lc-voice" type="button" title="Spraakbericht opnemen" aria-label="Spraakbericht opnemen">🎤</button><textarea class="lc-input" rows="1" maxlength="4000" aria-label="Bericht aan medewerker" placeholder="Schrijf je bericht…" required></textarea><button class="guest-chat__send" type="submit" aria-label="Bericht aan medewerker versturen">↑</button></form>
                <p class="guest-chat__notice">Je praat met een medewerker. Berichten worden bewaard voor ondersteuning. @guest Bewaar deze browsersessie om antwoorden te ontvangen. @endguest</p>
            </section>
        @endif
    </section>

    <button type="button" class="guest-chat__toggle" aria-expanded="false" aria-controls="guest-chat-panel" aria-label="Open Mashal chat"><span class="gc-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 11.5a8 8 0 0 1-11.5 7.2L3 21l1.8-5.7A8 8 0 1 1 20 11.5Z"/><path d="M8.5 11.5h7M12 8v7"/></svg></span><span class="gc-launch-copy"><strong>Mashal Support</strong><small>AI of live medewerker</small></span><span class="gc-launch-status" aria-hidden="true"></span><span class="gc-unread-badge" data-chat-unread aria-label="0 ongelezen berichten" hidden>0</span></button>
    <div class="gc-incoming-toast" data-chat-toast role="status" aria-live="polite" aria-atomic="true"><span class="gc-incoming-toast__icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 11.5a8 8 0 0 1-11.5 7.2L3 21l1.8-5.7A8 8 0 1 1 20 11.5Z"/></svg></span><span><strong>Nieuw bericht</strong><span data-chat-toast-text>Je hebt een nieuw bericht ontvangen.</span></span><span class="gc-incoming-toast__dot" aria-hidden="true"></span></div>
</aside>
<script src="{{ asset('js/guest-chat.js') }}?v=11" defer></script>
